# Code generated from mcp-tools.yaml. DO NOT EDIT.
# Generated by scripts/generate-tool-constants.py

"""MCP Tool Names - Single source of truth"""

# Server Information
SERVER_NAME = "url-db-mcp-server"
SERVER_VERSION = "1.0.0"
COMPOSITE_KEY_FORMAT = "url-db:domain:id"

# Tool Names

# Domain management operations
LIST_DOMAINS = "list_domains"
CREATE_DOMAIN = "create_domain"

# Node/URL CRUD operations
LIST_NODES = "list_nodes"
CREATE_NODE = "create_node"
GET_NODE = "get_node"
UPDATE_NODE = "update_node"
DELETE_NODE = "delete_node"
FIND_NODE_BY_URL = "find_node_by_url"

# Node attribute management
GET_NODE_ATTRIBUTES = "get_node_attributes"
SET_NODE_ATTRIBUTES = "set_node_attributes"

# Domain schema management
LIST_DOMAIN_ATTRIBUTES = "list_domain_attributes"
CREATE_DOMAIN_ATTRIBUTE = "create_domain_attribute"
GET_DOMAIN_ATTRIBUTE = "get_domain_attribute"
UPDATE_DOMAIN_ATTRIBUTE = "update_domain_attribute"
DELETE_DOMAIN_ATTRIBUTE = "delete_domain_attribute"

# Advanced query operations
GET_NODE_WITH_ATTRIBUTES = "get_node_with_attributes"
FILTER_NODES_BY_ATTRIBUTES = "filter_nodes_by_attributes"

# Server metadata and information
GET_SERVER_INFO = "get_server_info"

# Tool Descriptions
TOOL_DESCRIPTIONS = {
    LIST_DOMAINS: "Get all domains",
    CREATE_DOMAIN: "Create new domain for organizing URLs",
    LIST_NODES: "List URLs in domain",
    CREATE_NODE: "Add URL to domain",
    GET_NODE: "Get URL details",
    UPDATE_NODE: "Update URL title or description",
    DELETE_NODE: "Remove URL",
    FIND_NODE_BY_URL: "Search by exact URL",
    GET_NODE_ATTRIBUTES: "Get URL tags and attributes",
    SET_NODE_ATTRIBUTES: "Add or update URL tags",
    LIST_DOMAIN_ATTRIBUTES: "Get available tag types for domain",
    CREATE_DOMAIN_ATTRIBUTE: "Define new tag type for domain",
    GET_DOMAIN_ATTRIBUTE: "Get tag type details",
    UPDATE_DOMAIN_ATTRIBUTE: "Update tag type description",
    DELETE_DOMAIN_ATTRIBUTE: "Remove unused tag type",
    GET_NODE_WITH_ATTRIBUTES: "Get URL with all tags at once",
    FILTER_NODES_BY_ATTRIBUTES: "Search URLs by tag values",
    GET_SERVER_INFO: "Get server info",
}

# Tool Collections
ALL_TOOLS = [
    LIST_DOMAINS,
    CREATE_DOMAIN,
    LIST_NODES,
    CREATE_NODE,
    GET_NODE,
    UPDATE_NODE,
    DELETE_NODE,
    FIND_NODE_BY_URL,
    GET_NODE_ATTRIBUTES,
    SET_NODE_ATTRIBUTES,
    LIST_DOMAIN_ATTRIBUTES,
    CREATE_DOMAIN_ATTRIBUTE,
    GET_DOMAIN_ATTRIBUTE,
    UPDATE_DOMAIN_ATTRIBUTE,
    DELETE_DOMAIN_ATTRIBUTE,
    GET_NODE_WITH_ATTRIBUTES,
    FILTER_NODES_BY_ATTRIBUTES,
    GET_SERVER_INFO,
]

TOOL_CATEGORIES = {
    LIST_DOMAINS: "domain",
    CREATE_DOMAIN: "domain",
    LIST_NODES: "node",
    CREATE_NODE: "node",
    GET_NODE: "node",
    UPDATE_NODE: "node",
    DELETE_NODE: "node",
    FIND_NODE_BY_URL: "node",
    GET_NODE_ATTRIBUTES: "attribute",
    SET_NODE_ATTRIBUTES: "attribute",
    LIST_DOMAIN_ATTRIBUTES: "schema",
    CREATE_DOMAIN_ATTRIBUTE: "schema",
    GET_DOMAIN_ATTRIBUTE: "schema",
    UPDATE_DOMAIN_ATTRIBUTE: "schema",
    DELETE_DOMAIN_ATTRIBUTE: "schema",
    GET_NODE_WITH_ATTRIBUTES: "query",
    FILTER_NODES_BY_ATTRIBUTES: "query",
    GET_SERVER_INFO: "meta",
}

DOMAIN_TOOLS = [
    LIST_DOMAINS,
    CREATE_DOMAIN,
]

NODE_TOOLS = [
    LIST_NODES,
    CREATE_NODE,
    GET_NODE,
    UPDATE_NODE,
    DELETE_NODE,
    FIND_NODE_BY_URL,
]

ATTRIBUTE_TOOLS = [
    GET_NODE_ATTRIBUTES,
    SET_NODE_ATTRIBUTES,
]

SCHEMA_TOOLS = [
    LIST_DOMAIN_ATTRIBUTES,
    CREATE_DOMAIN_ATTRIBUTE,
    GET_DOMAIN_ATTRIBUTE,
    UPDATE_DOMAIN_ATTRIBUTE,
    DELETE_DOMAIN_ATTRIBUTE,
]

QUERY_TOOLS = [
    GET_NODE_WITH_ATTRIBUTES,
    FILTER_NODES_BY_ATTRIBUTES,
]

META_TOOLS = [
    GET_SERVER_INFO,
]

